function Foot = contPoint(in1,in2)
%CONTPOINT
%    FOOT = CONTPOINT(IN1,IN2)
%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    21-Jan-2017 02:04:03

alpha = in1(4,:);
beta = in1(5,:);
lH = in2(:,3);
lL2 = in2(:,7);
lL3 = in2(:,11);
phi = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = alpha+phi;
t3 = alpha+beta+phi;
Foot = [x+lH.*sin(phi)+lL2.*sin(t2)+lL3.*sin(t3);y-lH.*cos(phi)-lL2.*cos(t2)-lL3.*cos(t3)];
