function E = energy(in1,in2)
%ENERGY
%    E = ENERGY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    29-Jan-2017 00:17:38

J1 = in2(:,2);
J2 = in2(:,5);
J3 = in2(:,9);
alpha = in1(4,:);
beta = in1(5,:);
g = in2(:,12);
l2 = in2(:,6);
l3 = in2(:,10);
lH = in2(:,3);
lL2 = in2(:,7);
m1 = in2(:,1);
m2 = in2(:,4);
m3 = in2(:,8);
phi = in1(3,:);
valpha = in1(9,:);
vbeta = in1(10,:);
vphi = in1(8,:);
vx = in1(6,:);
vy = in1(7,:);
y = in1(2,:);
t2 = alpha+phi;
t3 = sin(t2);
t4 = lL2.*t3;
t5 = alpha+beta+phi;
t6 = sin(t5);
t7 = l3.*t6;
t19 = sin(phi);
t20 = lH.*t19;
t8 = vy+valpha.*(t4+t7)+vphi.*(t4+t7+t20)+l3.*t6.*vbeta;
t9 = cos(t2);
t10 = lL2.*t9;
t11 = cos(t5);
t12 = l3.*t11;
t16 = cos(phi);
t17 = lH.*t16;
t13 = vx+valpha.*(t10+t12)+vphi.*(t10+t12+t17)+l3.*t11.*vbeta;
t14 = valpha+vphi;
t15 = valpha+vbeta+vphi;
t22 = l2.*t9;
t18 = vx+vphi.*(t17+t22)+l2.*t9.*valpha;
t21 = vy+vphi.*(t20+l2.*t3)+l2.*t3.*valpha;
E = J2.*t14.^2.*(1.0./2.0)+J3.*t15.^2.*(1.0./2.0)+J1.*vphi.^2.*(1.0./2.0)+m3.*(t8.^2+t13.^2).*(1.0./2.0)+m2.*(t18.^2+t21.^2).*(1.0./2.0)+m1.*(vx.^2+vy.^2).*(1.0./2.0)-g.*m2.*(t17+t22-y)+g.*m1.*y-g.*m3.*(t10+t12+t17-y);
