function theta = Theta(in1,in2)
%THETA
%    THETA = THETA(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    07-Feb-2017 21:55:54

alpha = in1(4,:);
beta = in1(5,:);
l2 = in2(:,6);
l3 = in2(:,10);
lH = in2(:,3);
lL2 = in2(:,7);
lL3 = in2(:,11);
m1 = in2(:,1);
m2 = in2(:,4);
m3 = in2(:,8);
phi = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = alpha+phi;
t3 = sin(t2);
t4 = sin(phi);
t5 = lH.*t4;
t6 = alpha+beta+phi;
t7 = sin(t6);
t8 = cos(t2);
t9 = cos(phi);
t10 = lH.*t9;
t11 = lL2.*t8;
t12 = cos(t6);
t13 = m1+m2+m3;
t14 = 1.0./t13;
theta = angle(t10+t11+x.*1i-y+lH.*t4.*1i+lL2.*t3.*1i+lL3.*t7.*1i+lL3.*t12-t14.*(m3.*(t10+t11-y+l3.*t12)-m1.*y+m2.*(t10-y+l2.*t8))-t14.*(m1.*x+m2.*(t5+x+l2.*t3)+m3.*(t5+x+l3.*t7+lL2.*t3)).*1i);
