function CoG_tot = CoG_tot(in1,in2)
%COG_TOT
%    COG_TOT = COG_TOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    07-Feb-2017 22:51:59

alpha = in1(4,:);
beta = in1(5,:);
l2 = in2(:,6);
l3 = in2(:,10);
lH = in2(:,3);
lL2 = in2(:,7);
m1 = in2(:,1);
m2 = in2(:,4);
m3 = in2(:,8);
phi = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = alpha+phi;
t3 = sin(t2);
t4 = sin(phi);
t5 = lH.*t4;
t6 = cos(t2);
t7 = cos(phi);
t8 = lH.*t7;
t9 = alpha+beta+phi;
t10 = m1+m2+m3;
t11 = 1.0./t10;
CoG_tot = [t11.*(m3.*(t5+x+lL2.*t3+l3.*sin(t9))+m1.*x+m2.*(t5+x+l2.*t3));-t11.*(-m1.*y+m3.*(t8-y+lL2.*t6+l3.*cos(t9))+m2.*(t8-y+l2.*t6))];
