function fCG = FCorGrav(in1,in2)
%FCORGRAV
%    FCG = FCORGRAV(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    11-Feb-2017 01:07:15

alpha = in1(4,:);
beta = in1(5,:);
g = in2(:,12);
l2 = in2(:,6);
l3 = in2(:,10);
lH = in2(:,3);
lL2 = in2(:,7);
m1 = in2(:,1);
m2 = in2(:,4);
m3 = in2(:,8);
phi = in1(3,:);
valpha = in1(9,:);
vbeta = in1(10,:);
vphi = in1(8,:);
t2 = alpha+beta+phi;
t3 = sin(t2);
t4 = valpha.^2;
t5 = vphi.^2;
t6 = alpha+phi;
t7 = sin(t6);
t8 = sin(phi);
t9 = vbeta.^2;
t10 = cos(t2);
t11 = cos(t6);
t12 = cos(phi);
t13 = alpha+beta;
t14 = sin(t13);
t15 = sin(alpha);
t16 = sin(beta);
t17 = l3.*lL2.*m3.*t9.*t16;
t18 = l3.*lL2.*m3.*t16.*valpha.*vbeta.*2.0;
t19 = l3.*lL2.*m3.*t16.*vbeta.*vphi.*2.0;
fCG = [l3.*m3.*t3.*t4+l3.*m3.*t3.*t5+l2.*m2.*t4.*t7+l2.*m2.*t5.*t7+l3.*m3.*t3.*t9+lH.*m2.*t5.*t8+lH.*m3.*t5.*t8+lL2.*m3.*t4.*t7+lL2.*m3.*t5.*t7+l3.*m3.*t3.*valpha.*vbeta.*2.0+l3.*m3.*t3.*valpha.*vphi.*2.0+l2.*m2.*t7.*valpha.*vphi.*2.0+l3.*m3.*t3.*vbeta.*vphi.*2.0+lL2.*m3.*t7.*valpha.*vphi.*2.0;-g.*m1-g.*m2-g.*m3-l2.*m2.*t4.*t11-l2.*m2.*t5.*t11-l3.*m3.*t4.*t10-l3.*m3.*t5.*t10-l3.*m3.*t9.*t10-lH.*m2.*t5.*t12-lH.*m3.*t5.*t12-lL2.*m3.*t4.*t11-lL2.*m3.*t5.*t11-l3.*m3.*t10.*valpha.*vbeta.*2.0-l2.*m2.*t11.*valpha.*vphi.*2.0-l3.*m3.*t10.*valpha.*vphi.*2.0-l3.*m3.*t10.*vbeta.*vphi.*2.0-lL2.*m3.*t11.*valpha.*vphi.*2.0;t17+t18+t19-g.*l3.*m3.*t3-g.*l2.*m2.*t7-g.*lH.*m2.*t8-g.*lH.*m3.*t8-g.*lL2.*m3.*t7+l2.*lH.*m2.*t4.*t15+l3.*lH.*m3.*t4.*t14+l3.*lH.*m3.*t9.*t14+lH.*lL2.*m3.*t4.*t15+l3.*lH.*m3.*t14.*valpha.*vbeta.*2.0+l2.*lH.*m2.*t15.*valpha.*vphi.*2.0+l3.*lH.*m3.*t14.*valpha.*vphi.*2.0+l3.*lH.*m3.*t14.*vbeta.*vphi.*2.0+lH.*lL2.*m3.*t15.*valpha.*vphi.*2.0;t17+t18+t19-g.*l3.*m3.*t3-g.*l2.*m2.*t7-g.*lL2.*m3.*t7-l2.*lH.*m2.*t5.*t15-l3.*lH.*m3.*t5.*t14-lH.*lL2.*m3.*t5.*t15;-l3.*m3.*(g.*t3+lH.*t5.*t14+lL2.*t4.*t16+lL2.*t5.*t16+lL2.*t16.*valpha.*vphi.*2.0)];
