function CoG1 = posBody(in1,in2)
%POSBODY
%    COG1 = POSBODY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    29-Jan-2017 00:17:37

x = in1(1,:);
y = in1(2,:);
CoG1 = [x;y];
