function CoG1 = posBody(in1,in2)
%POSBODY
%    COG1 = POSBODY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    11-Feb-2017 01:07:15

x = in1(1,:);
y = in1(2,:);
CoG1 = [x;y];
