function Length = SpringLength(in1,in2)
%SPRINGLENGTH
%    LENGTH = SPRINGLENGTH(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    11-Feb-2017 01:07:28

alpha = in1(4,:);
beta = in1(5,:);
lH = in2(:,3);
lL2 = in2(:,7);
lL3 = in2(:,11);
phi = in1(3,:);
t3 = alpha+phi;
t4 = alpha+beta+phi;
t2 = lH.*cos(phi)+lL2.*cos(t3)+lL3.*cos(t4);
t5 = lH.*sin(phi)+lL2.*sin(t3)+lL3.*sin(t4);
Length = sqrt(t2.^2+t5.^2);
