function CoG1 = posBody(in1,in2)
%POSBODY
%    COG1 = POSBODY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    23-Jan-2017 17:42:44

x = in1(1,:);
y = in1(2,:);
CoG1 = [x;y];
