function CoG2 = CoGThigh(in1,in2)
%COGTHIGH
%    COG2 = COGTHIGH(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    08-Feb-2017 11:39:17

alpha = in1(4,:);
l2 = in2(:,6);
lH = in2(:,3);
phi = in1(3,:);
x = in1(1,:);
y = in1(2,:);
t2 = alpha+phi;
CoG2 = [x+lH.*sin(phi)+l2.*sin(t2);y-lH.*cos(phi)-l2.*cos(t2)];
