function J_reduced = J_virtual_force(phi_f,beta,alpha,lH,lL2,lL3)
%J_VIRTUAL_FORCE
%    J_REDUCED = J_VIRTUAL_FORCE(PHI_F,BETA,ALPHA,LH,LL2,LL3)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    01-Feb-2017 23:03:14

t2 = cos(phi_f);
t3 = beta+phi_f;
t4 = cos(t3);
t5 = lL2.*t4;
t6 = lL3.*t2;
t7 = alpha+beta+phi_f;
t8 = cos(t7);
t9 = lH.*t8;
t10 = t5+t6+t9;
t11 = 1.0./t10;
t12 = alpha+beta;
t13 = sin(t12);
J_reduced = reshape([-lL3.*t11.*(lH.*t13+lL2.*sin(beta)),-lH.*t11.*(lL3.*t13+lL2.*sin(alpha)),-lL3.*t2.*t11,-t11.*(t5+t6)],[2,2]);
